const single_breaches = {
    "8tracks": {
        "Name": "8tracks",
        "Title": "8tracks",
        "Domain": "8tracks.com",
        "BreachDate": "2017-06-27",
        "AddedDate": "2018-02-16T07:09:30Z",
        "ModifiedDate": "2018-02-16T07:09:30Z",
        "PwnCount": 7990619,
        "Description": "In June 2017, the online playlists service known as <a href=\"https://blog.8tracks.com/2017/06/27/password-security-alert/\" target=\"_blank\" rel=\"noopener\">8Tracks suffered a data breach</a> which impacted 18 million accounts. In their disclosure, 8Tracks advised that &quot;the vector for the attack was an employee’s GitHub account, which was not secured using two-factor authentication&quot;. Salted SHA-1 password hashes for users who <em>didn't</em> sign up with either Google or Facebook authentication were also included. The data was provided to HIBP by whitehat security researcher and data analyst Adam Davies and contained almost 8 million unique email addresses.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/8tracks.png",
        "DataClasses": [
            "Email addresses",
            "Passwords"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Adobe": {
        "Name": "Adobe",
        "Title": "Adobe",
        "Domain": "adobe.com",
        "BreachDate": "2013-10-04",
        "AddedDate": "2013-12-04T00:00:00Z",
        "ModifiedDate": "2013-12-04T00:00:00Z",
        "PwnCount": 152445165,
        "Description": "In October 2013, 153 million Adobe accounts were breached with each containing an internal ID, username, email, <em>encrypted</em> password and a password hint in plain text. The password cryptography was poorly done and <a href=\"http://stricture-group.com/files/adobe-top100.txt\" target=\"_blank\" rel=\"noopener\">many were quickly resolved back to plain text</a>. The unencrypted hints also <a href=\"http://www.troyhunt.com/2013/11/adobe-credentials-and-serious.html\" target=\"_blank\" rel=\"noopener\">disclosed much about the passwords</a> adding further to the risk that hundreds of millions of Adobe customers already faced.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Adobe.png",
        "DataClasses": [
            "Email addresses",
            "Password hints",
            "Passwords",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Apollo": {
        "Name": "Apollo",
        "Title": "Apollo",
        "Domain": "apollo.io",
        "BreachDate": "2018-07-23",
        "AddedDate": "2018-10-05T19:14:11Z",
        "ModifiedDate": "2018-10-23T04:01:48Z",
        "PwnCount": 125929660,
        "Description": "In July 2018, the sales engagement startup <a href=\"https://www.wired.com/story/apollo-breach-linkedin-salesforce-data/\" target=\"_blank\" rel=\"noopener\">Apollo left a database containing billions of data points publicly exposed without a password</a>. The data was discovered by security researcher <a href=\"http://www.vinnytroia.com/\" target=\"_blank\" rel=\"noopener\">Vinny Troia</a> who subsequently sent a subset of the data containing 126 million unique email addresses to Have I Been Pwned. The data left exposed by Apollo was used in their &quot;revenue acceleration platform&quot; and included personal information such as names and email addresses as well as professional information including places of employment, the roles people hold and where they're located. Apollo stressed that the exposed data did not include sensitive information such as passwords, social security numbers or financial data. <a href=\"https://www.apollo.io/contact\" target=\"_blank\" rel=\"noopener\">The Apollo website has a contact form</a> for those looking to get in touch with the organisation.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Apollo.png",
        "DataClasses": [
            "Email addresses",
            "Employers",
            "Geographic locations",
            "Job titles",
            "Names",
            "Phone numbers",
            "Salutations",
            "Social media profiles"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "BTSec": {
        "Name": "BTSec",
        "Title": "Bitcoin Security Forum Gmail Dump",
        "Domain": "forum.btcsec.com",
        "BreachDate": "2014-01-09",
        "AddedDate": "2014-09-10T20:30:11Z",
        "ModifiedDate": "2014-09-10T20:30:11Z",
        "PwnCount": 4789599,
        "Description": "In September 2014, a large dump of nearly 5M usernames and passwords was <a href=\"https://forum.btcsec.com/index.php?/topic/9426-gmail-meniai-parol/\" target=\"_blank\" rel=\"noopener\">posted to a Russian Bitcoin forum</a>. Whilst commonly reported as 5M &quot;Gmail passwords&quot;, the dump also contained 123k yandex.ru addresses. Whilst the origin of the breach remains unclear, the breached credentials were <a href=\"http://web.archive.org/web/20140910190920/http://www.reddit.com/r/netsec/comments/2fz13q/5_millions_of_gmail_passwords_leaked_rus_most/\" target=\"_blank\" rel=\"noopener\">confirmed by multiple source as correct</a>, albeit a number of years old.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/BTSec.png",
        "DataClasses": [
            "Email addresses",
            "Passwords"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "BlankMediaGames": {
        "Name": "BlankMediaGames",
        "Title": "BlankMediaGames",
        "Domain": "blankmediagames.com",
        "BreachDate": "2018-12-28",
        "AddedDate": "2019-01-02T05:52:56Z",
        "ModifiedDate": "2019-01-02T06:03:19Z",
        "PwnCount": 7633234,
        "Description": "In December 2018, the Town of Salem website produced by <a href=\"https://blog.dehashed.com/town-of-salem-blankmediagames-hacked/\" target=\"_blank\" rel=\"noopener\">BlankMediaGames suffered a data breach</a>. Reported to HIBP by <a href=\"https://dehashed.com/\" target=\"_blank\" rel=\"noopener\">DeHashed</a>, the data contained 7.6M unique user email addresses alongside usernames, IP addresses, purchase histories and passwords stored as phpass hashes. DeHashed made multiple attempts to contact BlankMediaGames over various channels and many days but had yet to receive a response at the time of publishing.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/BlankMediaGames.png",
        "DataClasses": [
            "Browser user agent details",
            "Email addresses",
            "IP addresses",
            "Passwords",
            "Purchases",
            "Usernames",
            "Website activity"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "CloudPets": {
        "Name": "CloudPets",
        "Title": "CloudPets",
        "Domain": "cloudpets.com",
        "BreachDate": "2017-01-01",
        "AddedDate": "2017-02-27T20:57:29Z",
        "ModifiedDate": "2017-02-27T20:57:29Z",
        "PwnCount": 583503,
        "Description": "In January, the maker of teddy bears that record children's voices and sends them to family and friends via the internet <a href=\"https://www.troyhunt.com/data-from-connected-cloudpets-teddy-bears-leaked-and-ransomed-exposing-kids-voice-messages\" target=\"_blank\" rel=\"noopener\">CloudPets left their database publicly exposed and it was subsequently downloaded by external parties</a> (the data was also subject to 3 different ransom demands). 583k records were provided to HIBP via a data trader and included email addresses and bcrypt hashes, but the full extent of user data exposed by the system was over 821k records and also included children's names and references to portrait photos and voice recordings.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/CloudPets.png",
        "DataClasses": [
            "Email addresses",
            "Family members' names",
            "Passwords"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Dailymotion": {
        "Name": "Dailymotion",
        "Title": "Dailymotion",
        "Domain": "dailymotion.com",
        "BreachDate": "2016-10-20",
        "AddedDate": "2017-08-07T02:51:12Z",
        "ModifiedDate": "2017-08-07T02:51:12Z",
        "PwnCount": 85176234,
        "Description": "In October 2016, the video sharing platform <a href=\"http://thehackernews.com/2016/12/dailymotion-video-hacked.html\" target=\"_blank\" rel=\"noopener\">Dailymotion suffered a data breach</a>. The attack led to the exposure of more than 85 million user accounts and included email addresses, usernames and bcrypt hashes of passwords.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Dailymotion.png",
        "DataClasses": [
            "Email addresses",
            "Passwords",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "DataAndLeads": {
        "Name": "DataAndLeads",
        "Title": "Data & Leads",
        "Domain": "datanleads.com",
        "BreachDate": "2018-11-14",
        "AddedDate": "2018-11-28T19:32:19Z",
        "ModifiedDate": "2018-11-28T19:32:19Z",
        "PwnCount": 44320330,
        "Description": "In November 2018, <a href=\"https://blog.hackenproof.com/industry-news/new-data-breach-exposes-57-million-records\" target=\"_blank\" rel=\"noopener\">security researcher Bob Diachenko identified an unprotected database believed to be hosted by a data aggregator</a>. Upon further investigation, the data was linked to marketing company <a href=\"http://web.archive.org/web/20180925092401/https://www.datanleads.com/\" target=\"_blank\" rel=\"noopener\">Data &amp; Leads</a>. The exposed Elasticsearch instance contained over 44M unique email addresses along with names, IP and physical addresses, phone numbers and employment information. No response was received from Data &amp; Leads when contacted by Bob and their site subsequently went offline.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png",
        "DataClasses": [
            "Email addresses",
            "Employers",
            "IP addresses",
            "Job titles",
            "Names",
            "Phone numbers",
            "Physical addresses"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Edmodo": {
        "Name": "Edmodo",
        "Title": "Edmodo",
        "Domain": "edmodo.com",
        "BreachDate": "2017-05-11",
        "AddedDate": "2017-06-01T05:59:24Z",
        "ModifiedDate": "2017-06-01T05:59:24Z",
        "PwnCount": 43423561,
        "Description": "In May 2017, the education platform <a href=\"https://motherboard.vice.com/en_us/article/hacker-steals-millions-of-user-account-details-from-education-platform-edmodo\" target=\"_blank\" rel=\"noopener\">Edmodo was hacked</a> resulting in the exposure of 77 million records comprised of over 43 million unique customer email addresses. The data was consequently published to a popular hacking forum and made freely available. The records in the breach included usernames, email addresses and bcrypt hashes of passwords.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Edmodo.png",
        "DataClasses": [
            "Email addresses",
            "Passwords",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Evony": {
        "Name": "Evony",
        "Title": "Evony",
        "Domain": "evony.com",
        "BreachDate": "2016-06-01",
        "AddedDate": "2017-03-25T23:43:45Z",
        "ModifiedDate": "2017-03-25T23:43:45Z",
        "PwnCount": 29396116,
        "Description": "In June 2016, the online multiplayer game <a href=\"http://securityaffairs.co/wordpress/52260/data-breach/evony-data-breach.html\" target=\"_blank\" rel=\"noopener\">Evony was hacked</a> and over 29 million unique accounts were exposed. The attack led to the exposure of usernames, email and IP addresses and MD5 hashes of passwords (without salt).",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Evony.png",
        "DataClasses": [
            "Email addresses",
            "IP addresses",
            "Passwords",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Exactis": {
        "Name": "Exactis",
        "Title": "Exactis",
        "Domain": "exactis.com",
        "BreachDate": "2018-06-01",
        "AddedDate": "2018-07-25T20:00:44Z",
        "ModifiedDate": "2018-07-25T20:00:44Z",
        "PwnCount": 131577763,
        "Description": "In June 2018, <a href=\"https://www.wired.com/story/exactis-database-leak-340-million-records/\" target=\"_blank\" rel=\"noopener\">the marketing firm Exactis inadvertently publicly leaked 340 million records of personal data</a>. Security researcher <a href=\"https://www.nightlionsecurity.com/\" target=\"_blank\" rel=\"noopener\">Vinny Troia of Night Lion Security</a> discovered the leak contained multiple terabytes of personal information spread across hundreds of separate fields including addresses, phone numbers, family structures and extensive profiling data. The data was collected as part of Exactis' service as a &quot;compiler and aggregator of premium business &amp; consumer data&quot; which they then sell for profiling and marketing purposes. A small subset of the exposed fields were provided to Have I Been Pwned and contained 132 million unique email addresses.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Exactis.png",
        "DataClasses": [
            "Credit status information",
            "Dates of birth",
            "Education levels",
            "Email addresses",
            "Ethnicities",
            "Family structure",
            "Financial investments",
            "Genders",
            "Home ownership statuses",
            "Income levels",
            "IP addresses",
            "Marital statuses",
            "Names",
            "Net worths",
            "Occupations",
            "Personal interests",
            "Phone numbers",
            "Physical addresses",
            "Religions",
            "Spoken languages"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "FashionFantasyGame": {
        "Name": "FashionFantasyGame",
        "Title": "FashionFantasyGame",
        "Domain": "fashionfantasygame.com",
        "BreachDate": "2016-12-01",
        "AddedDate": "2017-04-20T10:33:38Z",
        "ModifiedDate": "2017-04-20T10:33:38Z",
        "PwnCount": 2357872,
        "Description": "In late 2016, the fashion gaming website <a href=\"http://www.zdnet.com/article/amid-data-breach-responsibility-thrown-to-the-wind/\" target=\"_blank\" rel=\"noopener\">Fashion Fantasy Game suffered a data breach</a>. The incident exposed 2.3 million unique user accounts and corresponding MD5 password hashes with no salt. The data was contributed to Have I been pwned courtesy of rip@creep.im.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/FashionFantasyGame.png",
        "DataClasses": [
            "Email addresses",
            "Passwords"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Gaadi": {
        "Name": "Gaadi",
        "Title": "Gaadi",
        "Domain": "gaadi.com",
        "BreachDate": "2015-05-14",
        "AddedDate": "2018-07-01T07:17:02Z",
        "ModifiedDate": "2018-07-01T07:17:02Z",
        "PwnCount": 4261179,
        "Description": "In May 2015, the Indian motoring website known as <a href=\"https://www.gaadi.com/\" target=\"_blank\" rel=\"noopener\">Gaadi</a> had 4.3 million records exposed in a data breach. The data contained usernames, email and IP addresses, genders, the city of users as well as passwords stored in both plain text and as MD5 hashes. The site was previously reported as compromised on the <a href=\"https://vigilante.pw/\" target=\"_blank\" rel=\"noopener\">Vigilante.pw</a> breached database directory.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Gaadi.png",
        "DataClasses": [
            "Email addresses",
            "Genders",
            "Geographic locations",
            "IP addresses",
            "Names",
            "Passwords",
            "Phone numbers",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "iDressup": {
        "Name": "iDressup",
        "Title": "i-Dressup",
        "Domain": "i-dressup.com",
        "BreachDate": "2016-07-15",
        "AddedDate": "2016-09-26T20:14:51Z",
        "ModifiedDate": "2016-09-26T20:14:51Z",
        "PwnCount": 2191565,
        "Description": "In June 2016, the teen social site known as <a href=\"http://arstechnica.com/security/2016/09/social-hangout-site-for-teens-leaks-millions-of-plaintext-passwords/\" target=\"_blank\" rel=\"noopener\">i-Dressup was hacked</a> and over 2 million user accounts were exposed. At the time the hack was reported, the i-Dressup operators were not contactable and the underlying SQL injection flaw remained open, allegedly exposing a total of 5.5 million accounts. The breach included email addresses and passwords stored in plain text.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/iDressup.png",
        "DataClasses": [
            "Email addresses",
            "Passwords"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "iMesh": {
        "Name": "iMesh",
        "Title": "iMesh",
        "Domain": "imesh.com",
        "BreachDate": "2013-09-22",
        "AddedDate": "2016-07-02T05:42:13Z",
        "ModifiedDate": "2016-07-02T05:42:13Z",
        "PwnCount": 49467477,
        "Description": "In September 2013, the media and file sharing client known as <a href=\"http://www.ibtimes.co.uk/imesh-hack-more-51-million-user-records-former-filesharing-site-sale-dark-web-1565185\" target=\"_blank\" rel=\"noopener\">iMesh was hacked and approximately 50M accounts were exposed</a>. The data was later put up for sale on a dark market website in mid-2016 and included email and IP addresses, usernames and salted MD5 hashes.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/iMesh.png",
        "DataClasses": [
            "Email addresses",
            "IP addresses",
            "Passwords",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Lastfm": {
        "Name": "Lastfm",
        "Title": "Last.fm",
        "Domain": "last.fm",
        "BreachDate": "2012-03-22",
        "AddedDate": "2016-09-20T20:00:49Z",
        "ModifiedDate": "2016-09-20T20:00:49Z",
        "PwnCount": 37217682,
        "Description": "In March 2012, the music website <a href=\"https://techcrunch.com/2016/09/01/43-million-passwords-hacked-in-last-fm-breach/\" target=\"_blank\" rel=\"noopener\">Last.fm was hacked</a> and 43 million user accounts were exposed. Whilst <a href=\"http://www.last.fm/passwordsecurity\" target=\"_blank\" rel=\"noopener\">Last.fm knew of an incident back in 2012</a>, the scale of the hack was not known until the data was released publicly in September 2016. The breach included 37 million unique email addresses, usernames and passwords stored as unsalted MD5 hashes.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Lastfm.png",
        "DataClasses": [
            "Email addresses",
            "Passwords",
            "Usernames",
            "Website activity"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Leet": {
        "Name": "Leet",
        "Title": "Leet",
        "Domain": "leet.cc",
        "BreachDate": "2016-09-10",
        "AddedDate": "2016-09-30T22:00:48Z",
        "ModifiedDate": "2016-09-30T22:00:48Z",
        "PwnCount": 5081689,
        "Description": "In August 2016, the service for creating and running Pocket Minecraft edition servers known as <a href=\"http://news.softpedia.com/news/data-for-6-million-minecraft-gamers-stolen-from-leet-cc-servers-507445.shtml\" target=\"_blank\" rel=\"noopener\">Leet was reported as having suffered a data breach that impacted 6 million subscribers</a>. The incident reported by Softpedia had allegedly taken place earlier in the year, although the data set sent to HIBP was dated as recently as early September but contained only 2 million subscribers. The data included usernames, email and IP addresses and SHA512 hashes. A further 3 million accounts were obtained and added to HIBP several days after the initial data was loaded bringing the total to over 5 million.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Leet.png",
        "DataClasses": [
            "Email addresses",
            "IP addresses",
            "Passwords",
            "Usernames",
            "Website activity"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Lifeboat": {
        "Name": "Lifeboat",
        "Title": "Lifeboat",
        "Domain": "lbsg.net",
        "BreachDate": "2016-01-01",
        "AddedDate": "2016-04-25T21:51:50Z",
        "ModifiedDate": "2016-04-25T21:51:50Z",
        "PwnCount": 7089395,
        "Description": "In January 2016, the Minecraft community known as Lifeboat <a href=\"https://motherboard.vice.com/read/another-day-another-hack-7-million-emails-and-hashed-passwords-for-minecraft\" target=\"_blank\" rel=\"noopener\">was hacked and more than 7 million accounts leaked</a>. Lifeboat knew of the incident for three months before the breach was made public but elected not to advise customers. The leaked data included usernames, email addresses and passwords stored as straight MD5 hashes.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Lifeboat.png",
        "DataClasses": [
            "Email addresses",
            "Passwords",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "ModernBusinessSolutions": {
        "Name": "ModernBusinessSolutions",
        "Title": "Modern Business Solutions",
        "Domain": "modbsolutions.com",
        "BreachDate": "2016-10-08",
        "AddedDate": "2016-10-12T09:09:11Z",
        "ModifiedDate": "2016-10-12T09:09:11Z",
        "PwnCount": 58843488,
        "Description": "In October 2016, a large Mongo DB file containing tens of millions of accounts <a href=\"https://twitter.com/0x2Taylor/status/784544208879292417\" target=\"_blank\" rel=\"noopener\">was shared publicly on Twitter</a> (the file has since been removed). The database contained over 58M unique email addresses along with IP addresses, names, home addresses, genders, job titles, dates of birth and phone numbers. The data was subsequently <a href=\"http://news.softpedia.com/news/hacker-steals-58-million-user-records-from-data-storage-provider-509190.shtml\" target=\"_blank\" rel=\"noopener\">attributed to &quot;Modern Business Solutions&quot;</a>, a company that provides data storage and database hosting solutions. They've yet to acknowledge the incident or explain how they came to be in possession of the data.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/ModernBusinessSolutions.png",
        "DataClasses": [
            "Dates of birth",
            "Email addresses",
            "Genders",
            "IP addresses",
            "Job titles",
            "Names",
            "Phone numbers",
            "Physical addresses"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "MySpace": {
        "Name": "MySpace",
        "Title": "MySpace",
        "Domain": "myspace.com",
        "BreachDate": "2008-07-01",
        "AddedDate": "2016-05-31T00:12:29Z",
        "ModifiedDate": "2016-05-31T00:12:29Z",
        "PwnCount": 359420698,
        "Description": "In approximately 2008, <a href=\"http://motherboard.vice.com/read/427-million-myspace-passwords-emails-data-breach\" target=\"_blank\" rel=\"noopener\">MySpace suffered a data breach that exposed almost 360 million accounts</a>. In May 2016 the data was offered up for sale on the &quot;Real Deal&quot; dark market website and included email addresses, usernames and SHA1 hashes of the first 10 characters of the password converted to lowercase and stored without a salt. The exact breach date is unknown, but <a href=\"https://www.troyhunt.com/dating-the-ginormous-myspace-breach\" target=\"_blank\" rel=\"noopener\">analysis of the data suggests it was 8 years before being made public</a>.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/MySpace.png",
        "DataClasses": [
            "Email addresses",
            "Passwords",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "OnlinerSpambot": {
        "Name": "OnlinerSpambot",
        "Title": "Onliner Spambot",
        "Domain": "",
        "BreachDate": "2017-08-28",
        "AddedDate": "2017-08-29T19:25:56Z",
        "ModifiedDate": "2017-08-29T19:25:56Z",
        "PwnCount": 711477622,
        "Description": "In August 2017, a spambot by the name of <a href=\"https://benkowlab.blogspot.com.au/2017/08/from-onliner-spambot-to-millions-of.html\" target=\"_blank\" rel=\"noopener\">Onliner Spambot was identified by security researcher Benkow moʞuƎq</a>. The malicious software contained a server-based component located on an IP address in the Netherlands which exposed a large number of files containing personal information. In total, there were 711 million unique email addresses, many of which were also accompanied by corresponding passwords. A full write-up on what data was found is in the blog post titled <a href=\"https://www.troyhunt.com/inside-the-massive-711-million-record-onliner-spambot-dump\" target=\"_blank\" rel=\"noopener\">Inside the Massive 711 Million Record Onliner Spambot Dump</a>.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
        "DataClasses": [
            "Email addresses",
            "Passwords"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": true
    },
    "R2Games": {
        "Name": "R2Games",
        "Title": "R2Games",
        "Domain": "r2games.com",
        "BreachDate": "2015-11-01",
        "AddedDate": "2016-02-09T12:20:35Z",
        "ModifiedDate": "2016-02-09T12:20:35Z",
        "PwnCount": 22281337,
        "Description": "In late 2015, the gaming website <a href=\"https://www.r2games.com\" target=\"_blank\" rel=\"noopener\">R2Games</a> was hacked and more than 2.1M personal records disclosed. The vBulletin forum included IP addresses and passwords stored as salted hashes using a weak implementation enabling many to be rapidly cracked. A further 11M accounts were added to \"Have I been pwned\" in March 2016 and another 9M in July 2016 bringing the total to over 22M.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/R2Games.png",
        "DataClasses": [
            "Email addresses",
            "IP addresses",
            "Passwords",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "RiverCityMedia": {
        "Name": "RiverCityMedia",
        "Title": "River City Media Spam List",
        "Domain": "rivercitymediaonline.com",
        "BreachDate": "2017-01-01",
        "AddedDate": "2017-03-08T23:49:53Z",
        "ModifiedDate": "2017-03-08T23:49:53Z",
        "PwnCount": 393430309,
        "Description": "In January 2017, <a href=\"https://mackeeper.com/blog/post/339-spammergate-the-fall-of-an-empire\" target=\"_blank\" rel=\"noopener\">a massive trove of data from River City Media was found exposed online</a>. The data was found to contain almost 1.4 billion records including email and IP addresses, names and physical addresses, all of which was used as part of an enormous spam operation. Once de-duplicated, there were 393 million unique email addresses within the exposed data.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
        "DataClasses": [
            "Email addresses",
            "IP addresses",
            "Names",
            "Physical addresses"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": true
    },
    "SCDailyPhoneSpamList": {
        "Name": "SCDailyPhoneSpamList",
        "Title": "SC Daily Phone Spam List",
        "Domain": "data4marketers.com",
        "BreachDate": "2015-04-14",
        "AddedDate": "2016-11-24T06:04:34Z",
        "ModifiedDate": "2016-11-24T06:04:34Z",
        "PwnCount": 32939105,
        "Description": "In early 2015, a spam list known as <a href=\"http://www.data4marketers.com/2015APRspecials.html\" target=\"_blank\" rel=\"noopener\">SC Daily Phone</a> emerged containing almost 33M identities. The data includes personal attributes such as names, physical and IP addresses, genders, birth dates and phone numbers. <a href=\"https://www.troyhunt.com/have-i-been-pwned-and-spam-lists-of-personal-information\" target=\"_blank\" rel=\"noopener\">Read more about spam lists in HIBP.</a>",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
        "DataClasses": [
            "Dates of birth",
            "Email addresses",
            "Genders",
            "IP addresses",
            "Names",
            "Physical addresses"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": true
    },
    "Shotbow": {
        "Name": "Shotbow",
        "Title": "Shotbow",
        "Domain": "shotbow.net",
        "BreachDate": "2016-05-09",
        "AddedDate": "2017-10-29T23:53:20Z",
        "ModifiedDate": "2017-10-29T23:53:20Z",
        "PwnCount": 1052753,
        "Description": "In May 2016, the multiplayer server for Minecraft service <a href=\"https://shotbow.net/forum/threads/security-data-breach-and-information-leak.346321/\" target=\"_blank\" rel=\"noopener\">Shotbow announced they'd suffered a data breach</a>. The incident resulted in the exposure of over 1 million unique email addresses, usernames and salted SHA-256 password hashes.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Shotbow.png",
        "DataClasses": [
            "Email addresses",
            "Passwords",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "SpecialKSpamList": {
        "Name": "SpecialKSpamList",
        "Title": "Special K Data Feed Spam List",
        "Domain": "data4marketers.com",
        "BreachDate": "2015-10-07",
        "AddedDate": "2016-11-24T00:18:27Z",
        "ModifiedDate": "2016-11-24T00:18:27Z",
        "PwnCount": 30741620,
        "Description": "In mid to late 2015, a spam list known as the <a href=\"http://www.data4marketers.com/d4m_SpecialKfeed2015.html\" target=\"_blank\" rel=\"noopener\">Special K Data Feed</a> was discovered containing almost 31M identities. The data includes personal attributes such as names, physical and IP addresses, genders, birth dates and phone numbers. <a href=\"https://www.troyhunt.com/have-i-been-pwned-and-spam-lists-of-personal-information\" target=\"_blank\" rel=\"noopener\">Read more about spam lists in HIBP.</a>",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
        "DataClasses": [
            "Dates of birth",
            "Email addresses",
            "Genders",
            "IP addresses",
            "Names",
            "Physical addresses"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": true
    },
    "SterKinekor": {
        "Name": "SterKinekor",
        "Title": "Ster-Kinekor",
        "Domain": "sterkinekor.co.za",
        "BreachDate": "2017-03-09",
        "AddedDate": "2017-03-13T10:13:16Z",
        "ModifiedDate": "2017-03-13T10:13:16Z",
        "PwnCount": 1619544,
        "Description": "In 2016, the South African cinema company <a href=\"http://blog.roguecode.co.za/sterkinekor-vulnerability-download-millions-accounts\" target=\"_blank\" rel=\"noopener\">Ster-Kinekor had a security flaw</a> which leaked a large amount of customer data via an enumeration vulnerability in the API of their old website. Whilst more than 6 million accounts were leaked by the flaw, the exposed data only contained 1.6 million unique email addresses. The data also included extensive personal information such as names, addresses, birthdates, genders and plain text passwords.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/SterKinekor.png",
        "DataClasses": [
            "Dates of birth",
            "Email addresses",
            "Genders",
            "Names",
            "Passwords",
            "Phone numbers",
            "Physical addresses",
            "Spoken languages"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Ticketfly": {
        "Name": "Ticketfly",
        "Title": "Ticketfly",
        "Domain": "ticketfly.com",
        "BreachDate": "2018-05-31",
        "AddedDate": "2018-06-03T06:14:14Z",
        "ModifiedDate": "2018-07-14T06:06:15Z",
        "PwnCount": 26151608,
        "Description": "In May 2018, the website for the ticket distribution service <a href=\"https://motherboard.vice.com/en_us/article/mbk3nx/ticketfly-website-database-hacked-data-breach\" target=\"_blank\" rel=\"noopener\">Ticketfly was defaced by an attacker and was subsequently taken offline</a>. The attacker allegedly requested a ransom to share details of the vulnerability with Ticketfly but did not receive a reply and subsequently posted the breached data online to a publicly accessible location. The data included over 26 million unique email addresses along with names, physical addresses and phone numbers. Whilst there were no passwords in the publicly leaked data, <a href=https://support.ticketfly.com/customer/en/portal/articles/2941983-ticketfly-cyber-incident-update\" target=\"_blank\" rel=\"noopener\">Ticketfly later issued an incident update</a> and stated that &quot;It is possible, however, that hashed values of password credentials could have been accessed&quot;.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Ticketfly.png",
        "DataClasses": [
            "Email addresses",
            "Names",
            "Phone numbers",
            "Physical addresses"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Trillian": {
        "Name": "Trillian",
        "Title": "Trillian",
        "Domain": "trillian.im",
        "BreachDate": "2015-12-27",
        "AddedDate": "2016-07-15T11:14:44Z",
        "ModifiedDate": "2016-07-15T11:14:44Z",
        "PwnCount": 3827238,
        "Description": "In December 2015, the instant messaging application <a href=\"https://www.trillian.im/help/trillian-blog-and-forums-security-incident/\" target=\"_blank\" rel=\"noopener\">Trillian suffered a data breach</a>. The breach became known in July 2016 and exposed various personal data attributes including names, email addresses and passwords stored as salted MD5 hashes.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Trillian.png",
        "DataClasses": [
            "Dates of birth",
            "Email addresses",
            "IP addresses",
            "Names",
            "Passwords",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Tumblr": {
        "Name": "Tumblr",
        "Title": "tumblr",
        "Domain": "tumblr.com",
        "BreachDate": "2013-02-28",
        "AddedDate": "2016-05-29T22:59:04Z",
        "ModifiedDate": "2016-05-29T22:59:04Z",
        "PwnCount": 65469298,
        "Description": "In early 2013, <a href=\"https://staff.tumblr.com/post/144263069415/we-recently-learned-that-a-third-party-had\" target=\"_blank\" rel=\"noopener\">tumblr suffered a data breach</a> which resulted in the exposure of over 65 million accounts. The data was later put up for sale on a dark market website and included email addresses and passwords stored as salted SHA1 hashes.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Tumblr.png",
        "DataClasses": [
            "Email addresses",
            "Passwords"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "WeHeartIt": {
        "Name": "WeHeartIt",
        "Title": "We Heart It",
        "Domain": "weheartit.com",
        "BreachDate": "2013-11-03",
        "AddedDate": "2017-10-14T20:14:58Z",
        "ModifiedDate": "2017-10-14T20:14:58Z",
        "PwnCount": 8600635,
        "Description": "In November 2013, the image-based social network <a href=\"http://help.weheartit.com/customer/portal/articles/2889018\" target=\"_blank\" rel=\"noopener\">We Heart It suffered a data breach</a>. The incident wasn't discovered until October 2017 when 8.6 million user records were sent to HIBP. The data contained user names, email addresses and password hashes, 80% of which were salted SHA-256 with the remainder being MD5 with no salt.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/WeHeartIt.png",
        "DataClasses": [
            "Email addresses",
            "Passwords",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    },
    "Wishbone": {
        "Name": "Wishbone",
        "Title": "Wishbone",
        "Domain": "wishbone.io",
        "BreachDate": "2016-08-07",
        "AddedDate": "2017-03-15T19:29:52Z",
        "ModifiedDate": "2017-03-15T19:29:52Z",
        "PwnCount": 2247314,
        "Description": "In August 2016, the mobile app to &quot;compare anything&quot; known as <a href=\"https://motherboard.vice.com/en_us/article/popular-teen-quiz-app-wishbone-has-been-hacked-exposing-tons-of-user-information\" target=\"_blank\" rel=\"noopener\">Wishbone suffered a data breach</a>. The data contained 9.4 million records with 2.2 million unique email addresses and was allegedly a subset of the complete data set. The exposed data included genders, birthdates, email addresses and phone numbers for an audience predominantly composed of teenagers and young adults.",
        "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Wishbone.png",
        "DataClasses": [
            "Auth tokens",
            "Dates of birth",
            "Email addresses",
            "Genders",
            "Names",
            "Phone numbers",
            "Usernames"
        ],
        "IsVerified": true,
        "IsFabricated": false,
        "IsSensitive": false,
        "IsRetired": false,
        "IsSpamList": false
    }
};

const multi_breaches = { ...single_breaches };

export default {
    single_breaches,
    multi_breaches,
    results: {
        'courtney@gmail.com': ["8tracks", "Adobe", "Apollo", "BTSec", "BlankMediaGames", "CloudPets", "Dailymotion", "DataAndLeads", "Edmodo", "Evony", "Exactis", "FashionFantasyGame", "Gaadi", "iDressup", "iMesh", "Lastfm", "Leet", "Lifeboat", "ModernBusinessSolutions", "MySpace", "OnlinerSpambot", "R2Games", "RiverCityMedia", "SCDailyPhoneSpamList", "Shotbow", "SpecialKSpamList", "SterKinekor", "Ticketfly", "Trillian", "Tumblr", "WeHeartIt", "Wishbone"],
        'courtneypeacock@gmail.com': ["RiverCityMedia", "Tumblr"],
    },
    responses: {
        'courtney@gmail.com': [
            {
                "Name": "8tracks",
                "Title": "8tracks",
                "Domain": "8tracks.com",
                "BreachDate": "2017-06-27",
                "AddedDate": "2018-02-16T07:09:30Z",
                "ModifiedDate": "2018-02-16T07:09:30Z",
                "PwnCount": 7990619,
                "Description": "In June 2017, the online playlists service known as <a href=\"https://blog.8tracks.com/2017/06/27/password-security-alert/\" target=\"_blank\" rel=\"noopener\">8Tracks suffered a data breach</a> which impacted 18 million accounts. In their disclosure, 8Tracks advised that &quot;the vector for the attack was an employee’s GitHub account, which was not secured using two-factor authentication&quot;. Salted SHA-1 password hashes for users who <em>didn't</em> sign up with either Google or Facebook authentication were also included. The data was provided to HIBP by whitehat security researcher and data analyst Adam Davies and contained almost 8 million unique email addresses.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/8tracks.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Adobe",
                "Title": "Adobe",
                "Domain": "adobe.com",
                "BreachDate": "2013-10-04",
                "AddedDate": "2013-12-04T00:00:00Z",
                "ModifiedDate": "2013-12-04T00:00:00Z",
                "PwnCount": 152445165,
                "Description": "In October 2013, 153 million Adobe accounts were breached with each containing an internal ID, username, email, <em>encrypted</em> password and a password hint in plain text. The password cryptography was poorly done and <a href=\"http://stricture-group.com/files/adobe-top100.txt\" target=\"_blank\" rel=\"noopener\">many were quickly resolved back to plain text</a>. The unencrypted hints also <a href=\"http://www.troyhunt.com/2013/11/adobe-credentials-and-serious.html\" target=\"_blank\" rel=\"noopener\">disclosed much about the passwords</a> adding further to the risk that hundreds of millions of Adobe customers already faced.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Adobe.png",
                "DataClasses": [
                    "Email addresses",
                    "Password hints",
                    "Passwords",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Apollo",
                "Title": "Apollo",
                "Domain": "apollo.io",
                "BreachDate": "2018-07-23",
                "AddedDate": "2018-10-05T19:14:11Z",
                "ModifiedDate": "2018-10-23T04:01:48Z",
                "PwnCount": 125929660,
                "Description": "In July 2018, the sales engagement startup <a href=\"https://www.wired.com/story/apollo-breach-linkedin-salesforce-data/\" target=\"_blank\" rel=\"noopener\">Apollo left a database containing billions of data points publicly exposed without a password</a>. The data was discovered by security researcher <a href=\"http://www.vinnytroia.com/\" target=\"_blank\" rel=\"noopener\">Vinny Troia</a> who subsequently sent a subset of the data containing 126 million unique email addresses to Have I Been Pwned. The data left exposed by Apollo was used in their &quot;revenue acceleration platform&quot; and included personal information such as names and email addresses as well as professional information including places of employment, the roles people hold and where they're located. Apollo stressed that the exposed data did not include sensitive information such as passwords, social security numbers or financial data. <a href=\"https://www.apollo.io/contact\" target=\"_blank\" rel=\"noopener\">The Apollo website has a contact form</a> for those looking to get in touch with the organisation.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Apollo.png",
                "DataClasses": [
                    "Email addresses",
                    "Employers",
                    "Geographic locations",
                    "Job titles",
                    "Names",
                    "Phone numbers",
                    "Salutations",
                    "Social media profiles"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "BTSec",
                "Title": "Bitcoin Security Forum Gmail Dump",
                "Domain": "forum.btcsec.com",
                "BreachDate": "2014-01-09",
                "AddedDate": "2014-09-10T20:30:11Z",
                "ModifiedDate": "2014-09-10T20:30:11Z",
                "PwnCount": 4789599,
                "Description": "In September 2014, a large dump of nearly 5M usernames and passwords was <a href=\"https://forum.btcsec.com/index.php?/topic/9426-gmail-meniai-parol/\" target=\"_blank\" rel=\"noopener\">posted to a Russian Bitcoin forum</a>. Whilst commonly reported as 5M &quot;Gmail passwords&quot;, the dump also contained 123k yandex.ru addresses. Whilst the origin of the breach remains unclear, the breached credentials were <a href=\"http://web.archive.org/web/20140910190920/http://www.reddit.com/r/netsec/comments/2fz13q/5_millions_of_gmail_passwords_leaked_rus_most/\" target=\"_blank\" rel=\"noopener\">confirmed by multiple source as correct</a>, albeit a number of years old.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/BTSec.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "BlankMediaGames",
                "Title": "BlankMediaGames",
                "Domain": "blankmediagames.com",
                "BreachDate": "2018-12-28",
                "AddedDate": "2019-01-02T05:52:56Z",
                "ModifiedDate": "2019-01-02T06:03:19Z",
                "PwnCount": 7633234,
                "Description": "In December 2018, the Town of Salem website produced by <a href=\"https://blog.dehashed.com/town-of-salem-blankmediagames-hacked/\" target=\"_blank\" rel=\"noopener\">BlankMediaGames suffered a data breach</a>. Reported to HIBP by <a href=\"https://dehashed.com/\" target=\"_blank\" rel=\"noopener\">DeHashed</a>, the data contained 7.6M unique user email addresses alongside usernames, IP addresses, purchase histories and passwords stored as phpass hashes. DeHashed made multiple attempts to contact BlankMediaGames over various channels and many days but had yet to receive a response at the time of publishing.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/BlankMediaGames.png",
                "DataClasses": [
                    "Browser user agent details",
                    "Email addresses",
                    "IP addresses",
                    "Passwords",
                    "Purchases",
                    "Usernames",
                    "Website activity"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "CloudPets",
                "Title": "CloudPets",
                "Domain": "cloudpets.com",
                "BreachDate": "2017-01-01",
                "AddedDate": "2017-02-27T20:57:29Z",
                "ModifiedDate": "2017-02-27T20:57:29Z",
                "PwnCount": 583503,
                "Description": "In January, the maker of teddy bears that record children's voices and sends them to family and friends via the internet <a href=\"https://www.troyhunt.com/data-from-connected-cloudpets-teddy-bears-leaked-and-ransomed-exposing-kids-voice-messages\" target=\"_blank\" rel=\"noopener\">CloudPets left their database publicly exposed and it was subsequently downloaded by external parties</a> (the data was also subject to 3 different ransom demands). 583k records were provided to HIBP via a data trader and included email addresses and bcrypt hashes, but the full extent of user data exposed by the system was over 821k records and also included children's names and references to portrait photos and voice recordings.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/CloudPets.png",
                "DataClasses": [
                    "Email addresses",
                    "Family members' names",
                    "Passwords"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Dailymotion",
                "Title": "Dailymotion",
                "Domain": "dailymotion.com",
                "BreachDate": "2016-10-20",
                "AddedDate": "2017-08-07T02:51:12Z",
                "ModifiedDate": "2017-08-07T02:51:12Z",
                "PwnCount": 85176234,
                "Description": "In October 2016, the video sharing platform <a href=\"http://thehackernews.com/2016/12/dailymotion-video-hacked.html\" target=\"_blank\" rel=\"noopener\">Dailymotion suffered a data breach</a>. The attack led to the exposure of more than 85 million user accounts and included email addresses, usernames and bcrypt hashes of passwords.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Dailymotion.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "DataAndLeads",
                "Title": "Data & Leads",
                "Domain": "datanleads.com",
                "BreachDate": "2018-11-14",
                "AddedDate": "2018-11-28T19:32:19Z",
                "ModifiedDate": "2018-11-28T19:32:19Z",
                "PwnCount": 44320330,
                "Description": "In November 2018, <a href=\"https://blog.hackenproof.com/industry-news/new-data-breach-exposes-57-million-records\" target=\"_blank\" rel=\"noopener\">security researcher Bob Diachenko identified an unprotected database believed to be hosted by a data aggregator</a>. Upon further investigation, the data was linked to marketing company <a href=\"http://web.archive.org/web/20180925092401/https://www.datanleads.com/\" target=\"_blank\" rel=\"noopener\">Data &amp; Leads</a>. The exposed Elasticsearch instance contained over 44M unique email addresses along with names, IP and physical addresses, phone numbers and employment information. No response was received from Data &amp; Leads when contacted by Bob and their site subsequently went offline.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png",
                "DataClasses": [
                    "Email addresses",
                    "Employers",
                    "IP addresses",
                    "Job titles",
                    "Names",
                    "Phone numbers",
                    "Physical addresses"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Edmodo",
                "Title": "Edmodo",
                "Domain": "edmodo.com",
                "BreachDate": "2017-05-11",
                "AddedDate": "2017-06-01T05:59:24Z",
                "ModifiedDate": "2017-06-01T05:59:24Z",
                "PwnCount": 43423561,
                "Description": "In May 2017, the education platform <a href=\"https://motherboard.vice.com/en_us/article/hacker-steals-millions-of-user-account-details-from-education-platform-edmodo\" target=\"_blank\" rel=\"noopener\">Edmodo was hacked</a> resulting in the exposure of 77 million records comprised of over 43 million unique customer email addresses. The data was consequently published to a popular hacking forum and made freely available. The records in the breach included usernames, email addresses and bcrypt hashes of passwords.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Edmodo.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Evony",
                "Title": "Evony",
                "Domain": "evony.com",
                "BreachDate": "2016-06-01",
                "AddedDate": "2017-03-25T23:43:45Z",
                "ModifiedDate": "2017-03-25T23:43:45Z",
                "PwnCount": 29396116,
                "Description": "In June 2016, the online multiplayer game <a href=\"http://securityaffairs.co/wordpress/52260/data-breach/evony-data-breach.html\" target=\"_blank\" rel=\"noopener\">Evony was hacked</a> and over 29 million unique accounts were exposed. The attack led to the exposure of usernames, email and IP addresses and MD5 hashes of passwords (without salt).",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Evony.png",
                "DataClasses": [
                    "Email addresses",
                    "IP addresses",
                    "Passwords",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Exactis",
                "Title": "Exactis",
                "Domain": "exactis.com",
                "BreachDate": "2018-06-01",
                "AddedDate": "2018-07-25T20:00:44Z",
                "ModifiedDate": "2018-07-25T20:00:44Z",
                "PwnCount": 131577763,
                "Description": "In June 2018, <a href=\"https://www.wired.com/story/exactis-database-leak-340-million-records/\" target=\"_blank\" rel=\"noopener\">the marketing firm Exactis inadvertently publicly leaked 340 million records of personal data</a>. Security researcher <a href=\"https://www.nightlionsecurity.com/\" target=\"_blank\" rel=\"noopener\">Vinny Troia of Night Lion Security</a> discovered the leak contained multiple terabytes of personal information spread across hundreds of separate fields including addresses, phone numbers, family structures and extensive profiling data. The data was collected as part of Exactis' service as a &quot;compiler and aggregator of premium business &amp; consumer data&quot; which they then sell for profiling and marketing purposes. A small subset of the exposed fields were provided to Have I Been Pwned and contained 132 million unique email addresses.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Exactis.png",
                "DataClasses": [
                    "Credit status information",
                    "Dates of birth",
                    "Education levels",
                    "Email addresses",
                    "Ethnicities",
                    "Family structure",
                    "Financial investments",
                    "Genders",
                    "Home ownership statuses",
                    "Income levels",
                    "IP addresses",
                    "Marital statuses",
                    "Names",
                    "Net worths",
                    "Occupations",
                    "Personal interests",
                    "Phone numbers",
                    "Physical addresses",
                    "Religions",
                    "Spoken languages"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "FashionFantasyGame",
                "Title": "FashionFantasyGame",
                "Domain": "fashionfantasygame.com",
                "BreachDate": "2016-12-01",
                "AddedDate": "2017-04-20T10:33:38Z",
                "ModifiedDate": "2017-04-20T10:33:38Z",
                "PwnCount": 2357872,
                "Description": "In late 2016, the fashion gaming website <a href=\"http://www.zdnet.com/article/amid-data-breach-responsibility-thrown-to-the-wind/\" target=\"_blank\" rel=\"noopener\">Fashion Fantasy Game suffered a data breach</a>. The incident exposed 2.3 million unique user accounts and corresponding MD5 password hashes with no salt. The data was contributed to Have I been pwned courtesy of rip@creep.im.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/FashionFantasyGame.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Gaadi",
                "Title": "Gaadi",
                "Domain": "gaadi.com",
                "BreachDate": "2015-05-14",
                "AddedDate": "2018-07-01T07:17:02Z",
                "ModifiedDate": "2018-07-01T07:17:02Z",
                "PwnCount": 4261179,
                "Description": "In May 2015, the Indian motoring website known as <a href=\"https://www.gaadi.com/\" target=\"_blank\" rel=\"noopener\">Gaadi</a> had 4.3 million records exposed in a data breach. The data contained usernames, email and IP addresses, genders, the city of users as well as passwords stored in both plain text and as MD5 hashes. The site was previously reported as compromised on the <a href=\"https://vigilante.pw/\" target=\"_blank\" rel=\"noopener\">Vigilante.pw</a> breached database directory.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Gaadi.png",
                "DataClasses": [
                    "Email addresses",
                    "Genders",
                    "Geographic locations",
                    "IP addresses",
                    "Names",
                    "Passwords",
                    "Phone numbers",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "iDressup",
                "Title": "i-Dressup",
                "Domain": "i-dressup.com",
                "BreachDate": "2016-07-15",
                "AddedDate": "2016-09-26T20:14:51Z",
                "ModifiedDate": "2016-09-26T20:14:51Z",
                "PwnCount": 2191565,
                "Description": "In June 2016, the teen social site known as <a href=\"http://arstechnica.com/security/2016/09/social-hangout-site-for-teens-leaks-millions-of-plaintext-passwords/\" target=\"_blank\" rel=\"noopener\">i-Dressup was hacked</a> and over 2 million user accounts were exposed. At the time the hack was reported, the i-Dressup operators were not contactable and the underlying SQL injection flaw remained open, allegedly exposing a total of 5.5 million accounts. The breach included email addresses and passwords stored in plain text.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/iDressup.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "iMesh",
                "Title": "iMesh",
                "Domain": "imesh.com",
                "BreachDate": "2013-09-22",
                "AddedDate": "2016-07-02T05:42:13Z",
                "ModifiedDate": "2016-07-02T05:42:13Z",
                "PwnCount": 49467477,
                "Description": "In September 2013, the media and file sharing client known as <a href=\"http://www.ibtimes.co.uk/imesh-hack-more-51-million-user-records-former-filesharing-site-sale-dark-web-1565185\" target=\"_blank\" rel=\"noopener\">iMesh was hacked and approximately 50M accounts were exposed</a>. The data was later put up for sale on a dark market website in mid-2016 and included email and IP addresses, usernames and salted MD5 hashes.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/iMesh.png",
                "DataClasses": [
                    "Email addresses",
                    "IP addresses",
                    "Passwords",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Lastfm",
                "Title": "Last.fm",
                "Domain": "last.fm",
                "BreachDate": "2012-03-22",
                "AddedDate": "2016-09-20T20:00:49Z",
                "ModifiedDate": "2016-09-20T20:00:49Z",
                "PwnCount": 37217682,
                "Description": "In March 2012, the music website <a href=\"https://techcrunch.com/2016/09/01/43-million-passwords-hacked-in-last-fm-breach/\" target=\"_blank\" rel=\"noopener\">Last.fm was hacked</a> and 43 million user accounts were exposed. Whilst <a href=\"http://www.last.fm/passwordsecurity\" target=\"_blank\" rel=\"noopener\">Last.fm knew of an incident back in 2012</a>, the scale of the hack was not known until the data was released publicly in September 2016. The breach included 37 million unique email addresses, usernames and passwords stored as unsalted MD5 hashes.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Lastfm.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords",
                    "Usernames",
                    "Website activity"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Leet",
                "Title": "Leet",
                "Domain": "leet.cc",
                "BreachDate": "2016-09-10",
                "AddedDate": "2016-09-30T22:00:48Z",
                "ModifiedDate": "2016-09-30T22:00:48Z",
                "PwnCount": 5081689,
                "Description": "In August 2016, the service for creating and running Pocket Minecraft edition servers known as <a href=\"http://news.softpedia.com/news/data-for-6-million-minecraft-gamers-stolen-from-leet-cc-servers-507445.shtml\" target=\"_blank\" rel=\"noopener\">Leet was reported as having suffered a data breach that impacted 6 million subscribers</a>. The incident reported by Softpedia had allegedly taken place earlier in the year, although the data set sent to HIBP was dated as recently as early September but contained only 2 million subscribers. The data included usernames, email and IP addresses and SHA512 hashes. A further 3 million accounts were obtained and added to HIBP several days after the initial data was loaded bringing the total to over 5 million.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Leet.png",
                "DataClasses": [
                    "Email addresses",
                    "IP addresses",
                    "Passwords",
                    "Usernames",
                    "Website activity"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Lifeboat",
                "Title": "Lifeboat",
                "Domain": "lbsg.net",
                "BreachDate": "2016-01-01",
                "AddedDate": "2016-04-25T21:51:50Z",
                "ModifiedDate": "2016-04-25T21:51:50Z",
                "PwnCount": 7089395,
                "Description": "In January 2016, the Minecraft community known as Lifeboat <a href=\"https://motherboard.vice.com/read/another-day-another-hack-7-million-emails-and-hashed-passwords-for-minecraft\" target=\"_blank\" rel=\"noopener\">was hacked and more than 7 million accounts leaked</a>. Lifeboat knew of the incident for three months before the breach was made public but elected not to advise customers. The leaked data included usernames, email addresses and passwords stored as straight MD5 hashes.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Lifeboat.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "ModernBusinessSolutions",
                "Title": "Modern Business Solutions",
                "Domain": "modbsolutions.com",
                "BreachDate": "2016-10-08",
                "AddedDate": "2016-10-12T09:09:11Z",
                "ModifiedDate": "2016-10-12T09:09:11Z",
                "PwnCount": 58843488,
                "Description": "In October 2016, a large Mongo DB file containing tens of millions of accounts <a href=\"https://twitter.com/0x2Taylor/status/784544208879292417\" target=\"_blank\" rel=\"noopener\">was shared publicly on Twitter</a> (the file has since been removed). The database contained over 58M unique email addresses along with IP addresses, names, home addresses, genders, job titles, dates of birth and phone numbers. The data was subsequently <a href=\"http://news.softpedia.com/news/hacker-steals-58-million-user-records-from-data-storage-provider-509190.shtml\" target=\"_blank\" rel=\"noopener\">attributed to &quot;Modern Business Solutions&quot;</a>, a company that provides data storage and database hosting solutions. They've yet to acknowledge the incident or explain how they came to be in possession of the data.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/ModernBusinessSolutions.png",
                "DataClasses": [
                    "Dates of birth",
                    "Email addresses",
                    "Genders",
                    "IP addresses",
                    "Job titles",
                    "Names",
                    "Phone numbers",
                    "Physical addresses"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "MySpace",
                "Title": "MySpace",
                "Domain": "myspace.com",
                "BreachDate": "2008-07-01",
                "AddedDate": "2016-05-31T00:12:29Z",
                "ModifiedDate": "2016-05-31T00:12:29Z",
                "PwnCount": 359420698,
                "Description": "In approximately 2008, <a href=\"http://motherboard.vice.com/read/427-million-myspace-passwords-emails-data-breach\" target=\"_blank\" rel=\"noopener\">MySpace suffered a data breach that exposed almost 360 million accounts</a>. In May 2016 the data was offered up for sale on the &quot;Real Deal&quot; dark market website and included email addresses, usernames and SHA1 hashes of the first 10 characters of the password converted to lowercase and stored without a salt. The exact breach date is unknown, but <a href=\"https://www.troyhunt.com/dating-the-ginormous-myspace-breach\" target=\"_blank\" rel=\"noopener\">analysis of the data suggests it was 8 years before being made public</a>.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/MySpace.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "OnlinerSpambot",
                "Title": "Onliner Spambot",
                "Domain": "",
                "BreachDate": "2017-08-28",
                "AddedDate": "2017-08-29T19:25:56Z",
                "ModifiedDate": "2017-08-29T19:25:56Z",
                "PwnCount": 711477622,
                "Description": "In August 2017, a spambot by the name of <a href=\"https://benkowlab.blogspot.com.au/2017/08/from-onliner-spambot-to-millions-of.html\" target=\"_blank\" rel=\"noopener\">Onliner Spambot was identified by security researcher Benkow moʞuƎq</a>. The malicious software contained a server-based component located on an IP address in the Netherlands which exposed a large number of files containing personal information. In total, there were 711 million unique email addresses, many of which were also accompanied by corresponding passwords. A full write-up on what data was found is in the blog post titled <a href=\"https://www.troyhunt.com/inside-the-massive-711-million-record-onliner-spambot-dump\" target=\"_blank\" rel=\"noopener\">Inside the Massive 711 Million Record Onliner Spambot Dump</a>.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": true
            },
            {
                "Name": "R2Games",
                "Title": "R2Games",
                "Domain": "r2games.com",
                "BreachDate": "2015-11-01",
                "AddedDate": "2016-02-09T12:20:35Z",
                "ModifiedDate": "2016-02-09T12:20:35Z",
                "PwnCount": 22281337,
                "Description": "In late 2015, the gaming website <a href=\"https://www.r2games.com\" target=\"_blank\" rel=\"noopener\">R2Games</a> was hacked and more than 2.1M personal records disclosed. The vBulletin forum included IP addresses and passwords stored as salted hashes using a weak implementation enabling many to be rapidly cracked. A further 11M accounts were added to \"Have I been pwned\" in March 2016 and another 9M in July 2016 bringing the total to over 22M.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/R2Games.png",
                "DataClasses": [
                    "Email addresses",
                    "IP addresses",
                    "Passwords",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "RiverCityMedia",
                "Title": "River City Media Spam List",
                "Domain": "rivercitymediaonline.com",
                "BreachDate": "2017-01-01",
                "AddedDate": "2017-03-08T23:49:53Z",
                "ModifiedDate": "2017-03-08T23:49:53Z",
                "PwnCount": 393430309,
                "Description": "In January 2017, <a href=\"https://mackeeper.com/blog/post/339-spammergate-the-fall-of-an-empire\" target=\"_blank\" rel=\"noopener\">a massive trove of data from River City Media was found exposed online</a>. The data was found to contain almost 1.4 billion records including email and IP addresses, names and physical addresses, all of which was used as part of an enormous spam operation. Once de-duplicated, there were 393 million unique email addresses within the exposed data.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
                "DataClasses": [
                    "Email addresses",
                    "IP addresses",
                    "Names",
                    "Physical addresses"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": true
            },
            {
                "Name": "SCDailyPhoneSpamList",
                "Title": "SC Daily Phone Spam List",
                "Domain": "data4marketers.com",
                "BreachDate": "2015-04-14",
                "AddedDate": "2016-11-24T06:04:34Z",
                "ModifiedDate": "2016-11-24T06:04:34Z",
                "PwnCount": 32939105,
                "Description": "In early 2015, a spam list known as <a href=\"http://www.data4marketers.com/2015APRspecials.html\" target=\"_blank\" rel=\"noopener\">SC Daily Phone</a> emerged containing almost 33M identities. The data includes personal attributes such as names, physical and IP addresses, genders, birth dates and phone numbers. <a href=\"https://www.troyhunt.com/have-i-been-pwned-and-spam-lists-of-personal-information\" target=\"_blank\" rel=\"noopener\">Read more about spam lists in HIBP.</a>",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
                "DataClasses": [
                    "Dates of birth",
                    "Email addresses",
                    "Genders",
                    "IP addresses",
                    "Names",
                    "Physical addresses"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": true
            },
            {
                "Name": "Shotbow",
                "Title": "Shotbow",
                "Domain": "shotbow.net",
                "BreachDate": "2016-05-09",
                "AddedDate": "2017-10-29T23:53:20Z",
                "ModifiedDate": "2017-10-29T23:53:20Z",
                "PwnCount": 1052753,
                "Description": "In May 2016, the multiplayer server for Minecraft service <a href=\"https://shotbow.net/forum/threads/security-data-breach-and-information-leak.346321/\" target=\"_blank\" rel=\"noopener\">Shotbow announced they'd suffered a data breach</a>. The incident resulted in the exposure of over 1 million unique email addresses, usernames and salted SHA-256 password hashes.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Shotbow.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "SpecialKSpamList",
                "Title": "Special K Data Feed Spam List",
                "Domain": "data4marketers.com",
                "BreachDate": "2015-10-07",
                "AddedDate": "2016-11-24T00:18:27Z",
                "ModifiedDate": "2016-11-24T00:18:27Z",
                "PwnCount": 30741620,
                "Description": "In mid to late 2015, a spam list known as the <a href=\"http://www.data4marketers.com/d4m_SpecialKfeed2015.html\" target=\"_blank\" rel=\"noopener\">Special K Data Feed</a> was discovered containing almost 31M identities. The data includes personal attributes such as names, physical and IP addresses, genders, birth dates and phone numbers. <a href=\"https://www.troyhunt.com/have-i-been-pwned-and-spam-lists-of-personal-information\" target=\"_blank\" rel=\"noopener\">Read more about spam lists in HIBP.</a>",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
                "DataClasses": [
                    "Dates of birth",
                    "Email addresses",
                    "Genders",
                    "IP addresses",
                    "Names",
                    "Physical addresses"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": true
            },
            {
                "Name": "SterKinekor",
                "Title": "Ster-Kinekor",
                "Domain": "sterkinekor.co.za",
                "BreachDate": "2017-03-09",
                "AddedDate": "2017-03-13T10:13:16Z",
                "ModifiedDate": "2017-03-13T10:13:16Z",
                "PwnCount": 1619544,
                "Description": "In 2016, the South African cinema company <a href=\"http://blog.roguecode.co.za/sterkinekor-vulnerability-download-millions-accounts\" target=\"_blank\" rel=\"noopener\">Ster-Kinekor had a security flaw</a> which leaked a large amount of customer data via an enumeration vulnerability in the API of their old website. Whilst more than 6 million accounts were leaked by the flaw, the exposed data only contained 1.6 million unique email addresses. The data also included extensive personal information such as names, addresses, birthdates, genders and plain text passwords.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/SterKinekor.png",
                "DataClasses": [
                    "Dates of birth",
                    "Email addresses",
                    "Genders",
                    "Names",
                    "Passwords",
                    "Phone numbers",
                    "Physical addresses",
                    "Spoken languages"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Ticketfly",
                "Title": "Ticketfly",
                "Domain": "ticketfly.com",
                "BreachDate": "2018-05-31",
                "AddedDate": "2018-06-03T06:14:14Z",
                "ModifiedDate": "2018-07-14T06:06:15Z",
                "PwnCount": 26151608,
                "Description": "In May 2018, the website for the ticket distribution service <a href=\"https://motherboard.vice.com/en_us/article/mbk3nx/ticketfly-website-database-hacked-data-breach\" target=\"_blank\" rel=\"noopener\">Ticketfly was defaced by an attacker and was subsequently taken offline</a>. The attacker allegedly requested a ransom to share details of the vulnerability with Ticketfly but did not receive a reply and subsequently posted the breached data online to a publicly accessible location. The data included over 26 million unique email addresses along with names, physical addresses and phone numbers. Whilst there were no passwords in the publicly leaked data, <a href=https://support.ticketfly.com/customer/en/portal/articles/2941983-ticketfly-cyber-incident-update\" target=\"_blank\" rel=\"noopener\">Ticketfly later issued an incident update</a> and stated that &quot;It is possible, however, that hashed values of password credentials could have been accessed&quot;.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Ticketfly.png",
                "DataClasses": [
                    "Email addresses",
                    "Names",
                    "Phone numbers",
                    "Physical addresses"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Trillian",
                "Title": "Trillian",
                "Domain": "trillian.im",
                "BreachDate": "2015-12-27",
                "AddedDate": "2016-07-15T11:14:44Z",
                "ModifiedDate": "2016-07-15T11:14:44Z",
                "PwnCount": 3827238,
                "Description": "In December 2015, the instant messaging application <a href=\"https://www.trillian.im/help/trillian-blog-and-forums-security-incident/\" target=\"_blank\" rel=\"noopener\">Trillian suffered a data breach</a>. The breach became known in July 2016 and exposed various personal data attributes including names, email addresses and passwords stored as salted MD5 hashes.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Trillian.png",
                "DataClasses": [
                    "Dates of birth",
                    "Email addresses",
                    "IP addresses",
                    "Names",
                    "Passwords",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Tumblr",
                "Title": "tumblr",
                "Domain": "tumblr.com",
                "BreachDate": "2013-02-28",
                "AddedDate": "2016-05-29T22:59:04Z",
                "ModifiedDate": "2016-05-29T22:59:04Z",
                "PwnCount": 65469298,
                "Description": "In early 2013, <a href=\"https://staff.tumblr.com/post/144263069415/we-recently-learned-that-a-third-party-had\" target=\"_blank\" rel=\"noopener\">tumblr suffered a data breach</a> which resulted in the exposure of over 65 million accounts. The data was later put up for sale on a dark market website and included email addresses and passwords stored as salted SHA1 hashes.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Tumblr.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "WeHeartIt",
                "Title": "We Heart It",
                "Domain": "weheartit.com",
                "BreachDate": "2013-11-03",
                "AddedDate": "2017-10-14T20:14:58Z",
                "ModifiedDate": "2017-10-14T20:14:58Z",
                "PwnCount": 8600635,
                "Description": "In November 2013, the image-based social network <a href=\"http://help.weheartit.com/customer/portal/articles/2889018\" target=\"_blank\" rel=\"noopener\">We Heart It suffered a data breach</a>. The incident wasn't discovered until October 2017 when 8.6 million user records were sent to HIBP. The data contained user names, email addresses and password hashes, 80% of which were salted SHA-256 with the remainder being MD5 with no salt.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/WeHeartIt.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            },
            {
                "Name": "Wishbone",
                "Title": "Wishbone",
                "Domain": "wishbone.io",
                "BreachDate": "2016-08-07",
                "AddedDate": "2017-03-15T19:29:52Z",
                "ModifiedDate": "2017-03-15T19:29:52Z",
                "PwnCount": 2247314,
                "Description": "In August 2016, the mobile app to &quot;compare anything&quot; known as <a href=\"https://motherboard.vice.com/en_us/article/popular-teen-quiz-app-wishbone-has-been-hacked-exposing-tons-of-user-information\" target=\"_blank\" rel=\"noopener\">Wishbone suffered a data breach</a>. The data contained 9.4 million records with 2.2 million unique email addresses and was allegedly a subset of the complete data set. The exposed data included genders, birthdates, email addresses and phone numbers for an audience predominantly composed of teenagers and young adults.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Wishbone.png",
                "DataClasses": [
                    "Auth tokens",
                    "Dates of birth",
                    "Email addresses",
                    "Genders",
                    "Names",
                    "Phone numbers",
                    "Usernames"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            }
        ],
        "courtneypeacock@gmail.com": [
            {
                "Name": "RiverCityMedia",
                "Title": "River City Media Spam List",
                "Domain": "rivercitymediaonline.com",
                "BreachDate": "2017-01-01",
                "AddedDate": "2017-03-08T23:49:53Z",
                "ModifiedDate": "2017-03-08T23:49:53Z",
                "PwnCount": 393430309,
                "Description": "In January 2017, <a href=\"https://mackeeper.com/blog/post/339-spammergate-the-fall-of-an-empire\" target=\"_blank\" rel=\"noopener\">a massive trove of data from River City Media was found exposed online</a>. The data was found to contain almost 1.4 billion records including email and IP addresses, names and physical addresses, all of which was used as part of an enormous spam operation. Once de-duplicated, there were 393 million unique email addresses within the exposed data.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
                "DataClasses": [
                    "Email addresses",
                    "IP addresses",
                    "Names",
                    "Physical addresses"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": true
            },
            {
                "Name": "Tumblr",
                "Title": "tumblr",
                "Domain": "tumblr.com",
                "BreachDate": "2013-02-28",
                "AddedDate": "2016-05-29T22:59:04Z",
                "ModifiedDate": "2016-05-29T22:59:04Z",
                "PwnCount": 65469298,
                "Description": "In early 2013, <a href=\"https://staff.tumblr.com/post/144263069415/we-recently-learned-that-a-third-party-had\" target=\"_blank\" rel=\"noopener\">tumblr suffered a data breach</a> which resulted in the exposure of over 65 million accounts. The data was later put up for sale on a dark market website and included email addresses and passwords stored as salted SHA1 hashes.",
                "LogoPath": "https://haveibeenpwned.com/Content/Images/PwnedLogos/Tumblr.png",
                "DataClasses": [
                    "Email addresses",
                    "Passwords"
                ],
                "IsVerified": true,
                "IsFabricated": false,
                "IsSensitive": false,
                "IsRetired": false,
                "IsSpamList": false
            }
        ]
    }
};